#!/bin/bash 

#Method to display the main List

showList() {

  echo "Welcome to LunixStatus!"
  echo "Today's date is $(date)"
  echo "Current user is $(whoami)"
  echo "Linux version is $(uname -r)"
  echo ""
  echo "Select an option from list :"
  echo "1. List the running processes"
  echo "2. Check the memory status and free memory in the RAM"
  echo "3. Check the hard disk status and free memory in the HDD"
  echo "4. Check if apache is installed and return it's version"
  echo "5. Exit"
  echo ""
}


#Method to return the list of running processes

showRunningProcesses() {

  echo "Running processes are :"

  ps aux | less

}


#Method to display memory status and free memory in the RAM

showMemory(){
  echo "Memory status is:"
  free -h 
  echo ""
  echo "Free memory in RAM:"
  free -h | awk '/^Mem:/ {print $NF}'
  echo ""
}

#Method to  check the hard disk status and free memory in the HDD

showDisk(){
  echo "Disk usage:"
  df -h
  echo ""
  echo "Free memory in HDD:"
  df -h | awk '/^\/dev/{print $4}'
  echo ""
}

#Method to check if apache is installed and return it's version

checkApache(){

  if ! command -v apache2 > /dev/null; then
     echo "Apache is not installed"

  else
     echo "Apache version:"
     apache2 -v | grep "version"

  fi
}

# Main script
 
showList

#Method to display main view 

mainView(){
 while true; do
     
     read -p "Enter a choice from 1 to 5:" choice
     case $choice in
         1)

             showRunningProcesses
             subMenu
             ;;
         2)

             showMemory
             subMenu
             ;;

         3)

             showDisk
             subMenu
             ;;
         4)

             checkApache
             subMenu
             ;;
         5)

             exit 0
             ;;
         *)

             echo "invalid choice"
             sleep 1
             ;;

   esac

 done
}


# parse command line arguments
subMenu() {

  while true; do
      echo "select an option:"
      echo "1. Back to main view"
      echo "2. Update the view"
      echo "3. Exit"
      read -p "Enter your choice (1-3): " sub_choice
      case $sub_choice in
         1)
            showList
            mainView
            ;;
         2)       

            break
            ;; 
         3)         

            exit 0
            ;;
         *)

            echo "invalid choice"
            sleep 1
            ;;

     esac
 done

}



if [ -n "$1" ]; then 
    for arg in "$@"; do
        case "$arg" in
           p) 
           
               showRunningProcesses
               ;;
               
           r)  
               showMemory
               ;;
               
           h)  
               showDisk
               ;;
               
           a) 
               checkApache
               ;;
               
           *)  
               echo "Invalid argument. valid arguments are p,r,h,a"
               exit 1
               ;;
               
         esac
     done

   exit 0

else 
   
   mainView
   
fi
